/* -LICENSE-START-
** Copyright (c) 2012 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

#pragma once

#include "stdafx.h"
#include "BMDSwitcherAPI_h.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

// This file contains Callback and Monitor classes.
//
// Callback classes implement SDK callback interfaces to forward
// callback results to the main thread where it is safe to update the UI.
// Windows messages are posted to acheive this.
//
// Monitor classes register callbacks against SDK interfaces.

// Application defined messages for signalling callback results to main thread
#define WM_SWITCHER_DISCONNECTED								WM_APP+1
#define WM_MEDIA_PLAYER_SOURCE_CHANGED							WM_APP+2
#define WM_MEDIA_PLAYER_PLAYING_CHANGED							WM_APP+3
#define WM_MEDIA_PLAYER_LOOP_CHANGED							WM_APP+4
#define WM_MEDIA_PLAYER_BEGIN_CHANGED							WM_APP+5
#define WM_STILL_NAME_VALID_CHANGED								WM_APP+6
#define WM_CLIP_NAME_VALID_CHANGED								WM_APP+7
#define WM_STILLS_LOCK_OBTAINED									WM_APP+8
#define WM_CLIP_LOCK_OBTAINED									WM_APP+9
#define WM_STILLS_TRANSFER_ENDED								WM_APP+10
#define WM_CLIP_TRANSFER_ENDED									WM_APP+11

// Media player callback class
class MediaPlayerCallback : public IBMDSwitcherMediaPlayerCallback
{
public:
	MediaPlayerCallback(HWND hWnd);

	// IUnknown
	HRESULT STDMETHODCALLTYPE	QueryInterface(REFIID iid, LPVOID *ppv);
	ULONG STDMETHODCALLTYPE		AddRef(void);
	ULONG STDMETHODCALLTYPE		Release(void);

	// IBMDSwitcherMediaPlayerCallback
	HRESULT STDMETHODCALLTYPE	SourceChanged(void);
	HRESULT STDMETHODCALLTYPE	PlayingChanged(void);
	HRESULT STDMETHODCALLTYPE	LoopChanged(void);
	HRESULT STDMETHODCALLTYPE	AtBeginningChanged(void);
	HRESULT STDMETHODCALLTYPE	ClipFrameChanged(void);

private:
	~MediaPlayerCallback(); // Call Release

	HWND						mHWnd;
	LONG						mRefCount;
};

// Class for monitoring changes to a media player interface
class MediaPlayerMonitor
{
public:
	MediaPlayerMonitor(HWND hWnd);
	~MediaPlayerMonitor();
	
	void setMediaPlayer(IBMDSwitcherMediaPlayer* mediaPlayer);
	void flush();

private:
	MediaPlayerCallback*		mCallback;
	IBMDSwitcherMediaPlayer*	mMediaPlayer;
};

// Stills callback class
class StillsCallback : public IBMDSwitcherStillsCallback
{
public:
	StillsCallback(HWND hWnd);

public:
	// IUnknown
	HRESULT STDMETHODCALLTYPE	QueryInterface(REFIID iid, LPVOID *ppv);
	ULONG STDMETHODCALLTYPE		AddRef(void);
	ULONG STDMETHODCALLTYPE		Release(void);

	// IBMDSwitcherStillsCallback
	HRESULT STDMETHODCALLTYPE	Notify(BMDSwitcherMediaPoolEventType eventType, IBMDSwitcherFrame *frame, int index);

private:
	~StillsCallback(); // Call Release()

	HWND						mHWnd;
	LONG						mRefCount;
};

// Class for monitoring changes to a stills interface
class StillsMonitor
{
public:
	StillsMonitor(HWND hWnd);
	~StillsMonitor();

	void setStills(IBMDSwitcherStills* stills);
	void flush();

private:
	StillsCallback*			mCallback;
	IBMDSwitcherStills*		mStills;
};

// Clip callback class
class ClipCallback : public IBMDSwitcherClipCallback
{
public:
	ClipCallback(HWND hWnd);

public:
	// IUnknown
	HRESULT STDMETHODCALLTYPE	QueryInterface(REFIID iid, LPVOID *ppv);
	ULONG STDMETHODCALLTYPE		AddRef(void);
	ULONG STDMETHODCALLTYPE		Release(void);

	// IBMDSwitcherClipCallback
	HRESULT STDMETHODCALLTYPE	Notify(BMDSwitcherMediaPoolEventType eventType,
									   IBMDSwitcherFrame *frame,
									   int frameIndex,
									   IBMDSwitcherAudio *audio,
									   int clipIndex);
private:
	~ClipCallback(); // Call Release()

	HWND						mHWnd;
	LONG						mRefCount;
};

// Class for monitoring changes to a clip interface
class ClipMonitor
{
public:
	ClipMonitor(HWND hWnd);
	~ClipMonitor();

	void setClip(IBMDSwitcherClip* clip);
	void flush();

private:
	ClipCallback*			mCallback;
	IBMDSwitcherClip*		mClip;
};

// Lock callback class used for obtaining lock as required
// for transfers and used in StillTransfer class.
class LockCallback : public IBMDSwitcherLockCallback
{
public:
	LockCallback(HWND hWnd, int clipIndex = -1); // do not set clipIndex for stills

	// IUnknown
 	HRESULT STDMETHODCALLTYPE	QueryInterface(REFIID iid, LPVOID *ppv);
	ULONG STDMETHODCALLTYPE		AddRef(void);
	ULONG STDMETHODCALLTYPE		Release(void);

	// IBMDSwitcherLockCallback
	HRESULT STDMETHODCALLTYPE	Obtained();

private:
	HWND						mHWnd;
	LONG						mRefCount;
	int							mClipIndex;
};

// Switcher callback class
class SwitcherCallback : public IBMDSwitcherCallback
{
public:
	SwitcherCallback(HWND hWnd);

	// IUnknown
	HRESULT STDMETHODCALLTYPE	QueryInterface(REFIID iid, LPVOID *ppv);
	ULONG STDMETHODCALLTYPE		AddRef(void);
	ULONG STDMETHODCALLTYPE		Release(void);

	// IBMDSwitcherCallback
	HRESULT STDMETHODCALLTYPE	Notify(BMDSwitcherEventType eventType, BMDSwitcherVideoMode coreVideoMode);

private:
	~SwitcherCallback(); // Call Release()

	HWND			mHWnd;
	LONG			mRefCount;
};

// Class for monitoring changes to a switcher interface
class SwitcherMonitor
{
public:
	SwitcherMonitor(HWND hWnd);
	~SwitcherMonitor();

	void setSwitcher(IBMDSwitcher* switcher);

private:
	SwitcherCallback*	mCallback;
	IBMDSwitcher*		mSwitcher;
};
