/* -LICENSE-START-
** Copyright (c) 2021 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

using BMDSwitcherAPI;

namespace SwitcherRecordCSharp
{
	/// <summary>
	/// Interaction logic for MainWindow.xaml
	/// </summary>
	public partial class MainWindow : Window
	{
		private SwitcherRecordAVDevice      switcherRecordAVDevice = null;
		private SwitcherMonitor             switcherMonitor = null;
		private SwitcherRecordAVMonitor     switcherRecordAVMonitor = null;
		private SwitcherRecordDiskMonitor   switcherRecordDiskMonitor = null;

		private CancellationTokenSource switcherDisconnectedCancel;
		private CancellationTokenSource windowClosingCancel;
		private CancellationTokenSource recordingStoppingCancel;

		public ObservableCollection<KeyValuePair<uint, string>> RecordDiskIdCollection { get; set; }

		private readonly IReadOnlyDictionary<_BMDSwitcherRecordAVState, string> RecordStatusString = new Dictionary<_BMDSwitcherRecordAVState, string>()
		{
			{ _BMDSwitcherRecordAVState.bmdSwitcherRecordAVStateIdle,       "Idle" },
			{ _BMDSwitcherRecordAVState.bmdSwitcherRecordAVStateRecording,  "Recording" },
			{ _BMDSwitcherRecordAVState.bmdSwitcherRecordAVStateStopping,   "Stopping" },
		};

		private readonly IReadOnlyDictionary<_BMDSwitcherRecordDiskStatus, string> RecordDiskStatusString = new Dictionary<_BMDSwitcherRecordDiskStatus, string>()
		{
			{ _BMDSwitcherRecordDiskStatus.bmdSwitcherRecordDiskIdle,           "Idle" },
			{ _BMDSwitcherRecordDiskStatus.bmdSwitcherRecordDiskUnformatted,    "Unformatted" },
			{ _BMDSwitcherRecordDiskStatus.bmdSwitcherRecordDiskActive,         "Active" },
			{ _BMDSwitcherRecordDiskStatus.bmdSwitcherRecordDiskRecording,      "Recording" },
		};

		private const uint InvalidRecordingTime = 0xffffffff;
		private const uint InvalidDiskId = 0xffffffff;
		private const int RecordStartMillisecondsTimeout = 5000;

		private void DispatchInMainWindow(Action action)
		{
			// Helper to ensure UI and switcher commands occur on MainWindow thread
			if (!Dispatcher.CheckAccess())
				Dispatcher.Invoke(action);
			else
				action.Invoke();
		}

		private static void EnableChildControls(DependencyObject parent, bool enable)
		{
			// Recursively find child elements and enable or disable
			for (int i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
			{
				var child = VisualTreeHelper.GetChild(parent, i);

				if (child is UIElement)
					((UIElement)child).IsEnabled = enable;

				EnableChildControls(child, enable);
			}
		}

		public MainWindow()
		{
			InitializeComponent();
		}

		// Record has started, start monitoring task
		private async void StartRecordMonitoring()
		{
			if (switcherRecordAVDevice != null)
			{
				try
				{
					buttonStartStopRecording.Content = "Stop Recording";
					EnableChildControls(groupBoxRecordSettings, false);
					buttonConnect.IsEnabled = false;
					buttonSwitchDisk.IsEnabled = comboBoxDisk2.SelectedIndex >= 0;

					recordingStoppingCancel = new CancellationTokenSource();
					switcherDisconnectedCancel = new CancellationTokenSource();
					windowClosingCancel = new CancellationTokenSource();

					await switcherRecordAVDevice.TaskRecord(recordingStoppingCancel.Token, switcherDisconnectedCancel.Token, windowClosingCancel.Token);
				}
				catch (TaskCanceledException)
				{
				}
				finally
				{
					recordingStoppingCancel.Dispose();
					recordingStoppingCancel = null;

					switcherDisconnectedCancel.Dispose();
					switcherDisconnectedCancel = null;

					windowClosingCancel.Dispose();
					windowClosingCancel = null;

					buttonStartStopRecording.Content = "Start Recording";
					EnableChildControls(groupBoxRecordSettings, true);
					buttonConnect.IsEnabled = true;
					buttonSwitchDisk.IsEnabled = false;
				}
			}
		}

		private void RefreshDisk1Controls()
		{
			// Update binding
			comboBoxDisk1.DataContext = this;

			var disk1WorkingSet = switcherRecordAVDevice.Disk1WorkingSet;
			if (disk1WorkingSet < comboBoxDisk1.Items.Count)
			{
				comboBoxDisk1.SelectedValue = disk1WorkingSet;
				textBoxDisk1Status.Text = GetDiskStatusString(switcherRecordAVDevice.GetDiskStatus(disk1WorkingSet));
				textBoxDisk1Duration.Text = RecordingTimeToString(switcherRecordAVDevice.GetDiskRecordingTimeAvailable(disk1WorkingSet));
			}
			else
			{
				comboBoxDisk1.SelectedIndex = -1;   // No selection
				textBoxDisk1Status.Text = String.Empty;
				textBoxDisk1Duration.Text = String.Empty;
			}
		}

		private void RefreshDisk2Controls()
		{
			// Update binding
			comboBoxDisk2.DataContext = this;

			var disk2WorkingSet = switcherRecordAVDevice.Disk2WorkingSet;
			if (disk2WorkingSet < comboBoxDisk2.Items.Count)
			{
				comboBoxDisk2.SelectedValue = disk2WorkingSet;
				textBoxDisk2Status.Text = GetDiskStatusString(switcherRecordAVDevice.GetDiskStatus(disk2WorkingSet));
				textBoxDisk2Duration.Text = RecordingTimeToString(switcherRecordAVDevice.GetDiskRecordingTimeAvailable(disk2WorkingSet));
			}
			else
			{
				comboBoxDisk2.SelectedIndex = -1;   // No selection
				textBoxDisk2Status.Text = String.Empty;
				textBoxDisk2Duration.Text = String.Empty;
			}
		}

		private void SetIPAddressTextBoxEnabled(bool enabled)
		{
			textBoxIPAddr1.IsEnabled = enabled;
			textBoxIPAddr2.IsEnabled = enabled;
			textBoxIPAddr3.IsEnabled = enabled;
			textBoxIPAddr4.IsEnabled = enabled;
		}

		private bool HandleIPAddressEntry(string ipAddressString, bool moveFocusOnPeriod)
		{
			bool enteredPeriod = moveFocusOnPeriod && ipAddressString.EndsWith(".");
			bool ipAddressIsValid = IsIpAddressByteValid(enteredPeriod ? ipAddressString.TrimEnd('.') : ipAddressString);

			if (enteredPeriod && ipAddressIsValid)
			{
				FocusNavigationDirection focusDirection = FocusNavigationDirection.Next;

				// MoveFocus takes a TraveralReqest as its argument.
				TraversalRequest request = new TraversalRequest(focusDirection);

				// Gets the element with keyboard focus.
				UIElement elementWithFocus = Keyboard.FocusedElement as UIElement;

				// Change keyboard focus.
				return elementWithFocus?.MoveFocus(request) ?? false;
			}

			return !ipAddressIsValid;
		}

		private bool HandleConnectEvent()
		{
			// Validate IP Address fields
			if (!IsIpAddressByteValid(textBoxIPAddr1.Text) ||
				!IsIpAddressByteValid(textBoxIPAddr2.Text) ||
				!IsIpAddressByteValid(textBoxIPAddr3.Text) ||
				!IsIpAddressByteValid(textBoxIPAddr4.Text))
				return true;

			string ipAddress = textBoxIPAddr1.Text + '.' + textBoxIPAddr2.Text + '.' + textBoxIPAddr3.Text + '.' + textBoxIPAddr4.Text;

			try
			{
				switcherRecordAVDevice = new SwitcherRecordAVDevice(ipAddress, switcherRecordAVMonitor, switcherRecordDiskMonitor, switcherMonitor);
			}
			catch (SwitcherConnectException e)
			{
				MessageBox.Show(e.Message, "Switcher Connection Error");
				return true;
			}
			catch (SwitcherRecordInvalidException e)
			{
				MessageBox.Show(e.Message, "Switcher Record Invalid Error");
				return true;
			}

			// Update UI with values from connected switcher
			textBoxProductName.Text = switcherRecordAVDevice.ProductName;
			textBoxFileBasename.Text = switcherRecordAVDevice.RecordingFilename;
			checkBoxRecordInAllCameras.IsChecked = switcherRecordAVDevice.RecordInAllCameras;
			checkBoxISORecording.Visibility = switcherRecordAVDevice.SupportsISORecording ? Visibility.Visible : Visibility.Collapsed;
			checkBoxISORecording.IsChecked = switcherRecordAVDevice.SupportsISORecording ? switcherRecordAVDevice.RecordAllISOInputs : false;

			UpdateRecordStatus(switcherRecordAVDevice.RecordStatus);
			statusBarItemTimecode.Text = switcherRecordAVDevice.TimecodeHMSString;
			statusBarRecordingTimeAvailable.Text = RecordingTimeToString(switcherRecordAVDevice.TotalRecordingTimeAvailable);

			var diskIdKeyValuePairs = switcherRecordAVDevice.AvailableDiskIds.Select(id => new KeyValuePair<uint, string>(id, switcherRecordAVDevice.GetDiskVolumeName(id)));
			RecordDiskIdCollection = new ObservableCollection<KeyValuePair<uint, string>>(diskIdKeyValuePairs);
			RefreshDisk1Controls();
			RefreshDisk2Controls();

			SetIPAddressTextBoxEnabled(false);
			buttonConnect.Content = "Disconnect";

			EnableChildControls(groupBoxRecordSettings, true);
			buttonStartStopRecording.IsEnabled = RecordDiskIdCollection.Count >= 0;

			if (switcherRecordAVDevice.IsRecording)
			{
				// Switcher is already recording, start record task
				StartRecordMonitoring();
			}

			return false;
		}

		private void HandleDisconnectEvent()
		{
			switcherRecordAVDevice?.Disable();
			switcherRecordAVDevice = null;

			SetIPAddressTextBoxEnabled(true);
			EnableChildControls(groupBoxRecordSettings, false);
			buttonStartStopRecording.IsEnabled = false;

			textBoxProductName.Clear();
			textBoxFileBasename.Clear();
			checkBoxRecordInAllCameras.IsChecked = false;
			checkBoxISORecording.IsChecked = false;

			comboBoxDisk1.SelectedIndex = -1;
			textBoxDisk1Status.Clear();
			textBoxDisk1Duration.Clear();
			comboBoxDisk2.SelectedIndex = -1;
			textBoxDisk2Status.Clear();
			textBoxDisk2Duration.Clear();

			buttonConnect.Content = "Connect";

			statusBarRecordStatus.Text = "Not connected";
			statusBarItemTimecode.Text = "00:00:00";
			statusBarRecordingTimeAvailable.Text = RecordingTimeToString(0);

		}

		private static bool IsIpAddressByteValid(string str)
		{
			return int.TryParse(str, out int i) && i >= 0 && i <= 255;
		}


		#region switcher_monitor_events
		private void SwitcherMonitor_SwitcherDisconnected(object sender, EventArgs e)
		{
			switcherDisconnectedCancel?.Cancel();
			DispatchInMainWindow(() => { HandleDisconnectEvent(); });
		}
		#endregion

		#region switcher_record_av_monitor_events
		private void SwitcherRecordAVMonitor_RecordAllISOInputsChanged(object sender, EventArgs e)
		{
			DispatchInMainWindow(() => { checkBoxISORecording.IsChecked = switcherRecordAVDevice.SupportsISORecording ? switcherRecordAVDevice.RecordAllISOInputs : false; });
		}

		private void SwitcherRecordAVMonitor_RecordInAllCamerasChanged(object sender, EventArgs e)
		{
			DispatchInMainWindow(() => { checkBoxRecordInAllCameras.IsChecked = switcherRecordAVDevice.RecordInAllCameras; });
		}

		private void SwitcherRecordAVMonitor_TimecodeChanged(object sender, EventArgs e)
		{
			DispatchInMainWindow(() => { statusBarItemTimecode.Text = switcherRecordAVDevice.TimecodeHMSString; });
		}

		private void SwitcherRecordAVMonitor_FilenameChanged(object sender, EventArgs e)
		{
			DispatchInMainWindow(() => { textBoxFileBasename.Text = switcherRecordAVDevice.RecordingFilename; });
		}

		private void SwitcherRecordAVMonitor_TotalRecordingTimeAvailableChanged(object sender, EventArgs e)
		{
			DispatchInMainWindow(() => { statusBarRecordingTimeAvailable.Text = RecordingTimeToString(switcherRecordAVDevice.TotalRecordingTimeAvailable); });
		}

		private void SwitcherRecordAVMonitor_WorkingSetChanged(object sender, WorkingSetEventArgs e)
		{
			DispatchInMainWindow(() =>
			{
				switch (e.WorkingSetIndex)
				{
					case 0:
						SetDisk1Selection(e.DiskId);
						break;

					case 1:
						SetDisk2Selection(e.DiskId);
						break;
				}
			});
		}

		private void SwitcherRecordAVMonitor_DiskAvailable(object sender, DiskAvailabilityEventArgs e)
		{
			DispatchInMainWindow(() =>
			{
				switcherRecordAVDevice.DiskWithIDAvailable(e.DiskID);

				RecordDiskIdCollection.Add(new KeyValuePair<uint, string>(e.DiskID, switcherRecordAVDevice.GetDiskVolumeName(e.DiskID)));
				RefreshDisk1Controls();
				RefreshDisk2Controls();

				buttonStartStopRecording.IsEnabled = RecordDiskIdCollection.Count > 0;
			});
		}

		private void SwitcherRecordAVMonitor_DiskRemoved(object sender, DiskAvailabilityEventArgs e)
		{
			DispatchInMainWindow(() =>
			{
				switcherRecordAVDevice.DiskWithIDRemoved(e.DiskID);

				RecordDiskIdCollection.Remove(RecordDiskIdCollection.First(id => id.Key.Equals(e.DiskID)));
				RefreshDisk1Controls();
				RefreshDisk2Controls();

				buttonStartStopRecording.IsEnabled = RecordDiskIdCollection.Count > 0;
			});
		}

		private void SwitcherRecordAVMonitor_StatusUpdated(object sender, StatusUpdatedEventArgs e)
		{
			if (e.StateType == _BMDSwitcherRecordAVState.bmdSwitcherRecordAVStateRecording)
			{
				// Recording has started, start monitoring task
				DispatchInMainWindow(() => { StartRecordMonitoring(); });
			}
			else if (e.StateType == _BMDSwitcherRecordAVState.bmdSwitcherRecordAVStateStopping)
			{
				// Recording is stopping, stop monitoring task
				recordingStoppingCancel?.Cancel();
			}

			UpdateRecordStatus(e.StateType);
		}

		private void UpdateRecordStatus(_BMDSwitcherRecordAVState state)
		{
			DispatchInMainWindow(() =>
			{
				string statusString;
				try
				{
					statusString = RecordStatusString[state];
				}
				catch (KeyNotFoundException)
				{
					statusString = "Invalid";
				}

				statusBarRecordStatus.Text = statusString;
			});
		}

		private string GetDiskStatusString(_BMDSwitcherRecordDiskStatus diskStatus)
		{
			try
			{
				return RecordDiskStatusString[diskStatus];
			}
			catch (KeyNotFoundException)
			{
				return "Invalid";
			}
		}

		private void SetDisk1Selection(uint diskId)
		{
			if (diskId == InvalidDiskId)
			{
				comboBoxDisk1.IsEnabled = false;
				comboBoxDisk1.SelectedIndex = -1;
				buttonStartStopRecording.IsEnabled = false;
				textBoxDisk1Status.Text = "";
				textBoxDisk1Duration.Text = "";
			}
			else
			{
				comboBoxDisk1.IsEnabled = true;
				comboBoxDisk1.SelectedValue = diskId;
				buttonStartStopRecording.IsEnabled = true;
			}
		}

		private void SetDisk2Selection(uint diskId)
		{
			if (diskId == InvalidDiskId)
			{
				comboBoxDisk2.IsEnabled = false;
				comboBoxDisk2.SelectedIndex = -1;
				buttonSwitchDisk.IsEnabled = false;
				textBoxDisk2Status.Text = "";
				textBoxDisk2Duration.Text = "";
			}
			else
			{
				comboBoxDisk2.IsEnabled = true;
				comboBoxDisk2.SelectedValue = diskId;
			}
		}

		private string RecordingTimeToString(uint recordingTime)
		{
			if (recordingTime == InvalidRecordingTime)
				recordingTime = 0;

			var recordingTimeMinutes = recordingTime / 60;
			return String.Format("{0:D} hr {1:D2} min", recordingTimeMinutes / 60, recordingTimeMinutes % 60);
		}

		private void SwitcherRecordAVMonitor_ErrorOccurred(object sender, RecordingErrorEventArgs e)
		{
			DispatchInMainWindow(() => { MessageBox.Show(e.Error, "Error"); });
		}
		#endregion

		#region switcher_record_disk_monitor_events
		private void SwitcherRecordDiskMonitor_VolumeNameChanged(object sender, RecordDiskEventArgs e)
		{
			DispatchInMainWindow(() =>
			{
				var idx = RecordDiskIdCollection.ToList<KeyValuePair<uint, string>>().FindIndex(item => item.Key.Equals(e.DiskID));
				if (idx == -1)
					return;

				RecordDiskIdCollection[idx] = new KeyValuePair<uint, string>(e.DiskID, switcherRecordAVDevice.GetDiskVolumeName(e.DiskID));
				comboBoxDisk1.GetBindingExpression(ComboBox.ItemsSourceProperty).UpdateTarget();
				comboBoxDisk2.GetBindingExpression(ComboBox.ItemsSourceProperty).UpdateTarget();
			});
		}

		private void SwitcherRecordDiskMonitor_RecordingTimeAvailableChanged(object sender, RecordDiskEventArgs e)
		{
			DispatchInMainWindow(() =>
			{
				if (comboBoxDisk1.SelectedValue?.Equals(e.DiskID) ?? false)
				{
					textBoxDisk1Duration.Text = RecordingTimeToString(switcherRecordAVDevice.GetDiskRecordingTimeAvailable(e.DiskID));
				}
				else if (comboBoxDisk2.SelectedValue?.Equals(e.DiskID) ?? false)
				{
					textBoxDisk2Duration.Text = RecordingTimeToString(switcherRecordAVDevice.GetDiskRecordingTimeAvailable(e.DiskID));
				}
			});
		}

		private void SwitcherRecordDiskMonitor_StatusChanged(object sender, RecordDiskEventArgs e)
		{
			DispatchInMainWindow(() =>
			{
				_BMDSwitcherRecordDiskStatus diskStatus = switcherRecordAVDevice.GetDiskStatus(e.DiskID);

				if (comboBoxDisk1.SelectedValue?.Equals(e.DiskID) ?? false)
				{
					textBoxDisk1Status.Text = GetDiskStatusString(diskStatus);
				}
				else if (comboBoxDisk2.SelectedValue?.Equals(e.DiskID) ?? false)
				{
					textBoxDisk2Status.Text = GetDiskStatusString(diskStatus);
				}
			});
		}
		#endregion

		#region uievents
		private void Window_Loaded(object sender, RoutedEventArgs e)
		{
			switcherMonitor = new SwitcherMonitor();
			switcherMonitor.SwitcherDisconnected += SwitcherMonitor_SwitcherDisconnected;

			switcherRecordAVMonitor = new SwitcherRecordAVMonitor();
			switcherRecordAVMonitor.RecordAllISOInputsChanged += SwitcherRecordAVMonitor_RecordAllISOInputsChanged;
			switcherRecordAVMonitor.RecordInAllCamerasChanged += SwitcherRecordAVMonitor_RecordInAllCamerasChanged;
			switcherRecordAVMonitor.TimecodeChanged += SwitcherRecordAVMonitor_TimecodeChanged;
			switcherRecordAVMonitor.FilenameChanged += SwitcherRecordAVMonitor_FilenameChanged;
			switcherRecordAVMonitor.TotalRecordingTimeAvailableChanged += SwitcherRecordAVMonitor_TotalRecordingTimeAvailableChanged;
			switcherRecordAVMonitor.WorkingSetChanged += SwitcherRecordAVMonitor_WorkingSetChanged;
			switcherRecordAVMonitor.DiskAvailable += SwitcherRecordAVMonitor_DiskAvailable;
			switcherRecordAVMonitor.DiskRemoved += SwitcherRecordAVMonitor_DiskRemoved;
			switcherRecordAVMonitor.StatusUpdated += SwitcherRecordAVMonitor_StatusUpdated;
			switcherRecordAVMonitor.ErrorOccurred += SwitcherRecordAVMonitor_ErrorOccurred;

			switcherRecordDiskMonitor = new SwitcherRecordDiskMonitor();
			switcherRecordDiskMonitor.VolumeNameChanged += SwitcherRecordDiskMonitor_VolumeNameChanged;
			switcherRecordDiskMonitor.RecordingTimeAvailableChanged += SwitcherRecordDiskMonitor_RecordingTimeAvailableChanged;
			switcherRecordDiskMonitor.StatusChanged += SwitcherRecordDiskMonitor_StatusChanged;

			// Keep settings button inactive until connection
			EnableChildControls(groupBoxRecordSettings, false);
			buttonStartStopRecording.IsEnabled = false;
			buttonSwitchDisk.IsEnabled = false;
		}

		private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
		{
			windowClosingCancel?.Cancel();

			switcherRecordAVDevice?.Disable();
			switcherRecordAVDevice = null;

			switcherMonitor.SwitcherDisconnected -= SwitcherMonitor_SwitcherDisconnected;

			switcherRecordAVMonitor.RecordAllISOInputsChanged -= SwitcherRecordAVMonitor_RecordAllISOInputsChanged;
			switcherRecordAVMonitor.RecordInAllCamerasChanged -= SwitcherRecordAVMonitor_RecordInAllCamerasChanged;
			switcherRecordAVMonitor.TimecodeChanged -= SwitcherRecordAVMonitor_TimecodeChanged;
			switcherRecordAVMonitor.FilenameChanged -= SwitcherRecordAVMonitor_FilenameChanged;
			switcherRecordAVMonitor.TotalRecordingTimeAvailableChanged -= SwitcherRecordAVMonitor_TotalRecordingTimeAvailableChanged;
			switcherRecordAVMonitor.WorkingSetChanged -= SwitcherRecordAVMonitor_WorkingSetChanged;
			switcherRecordAVMonitor.DiskAvailable -= SwitcherRecordAVMonitor_DiskAvailable;
			switcherRecordAVMonitor.DiskRemoved -= SwitcherRecordAVMonitor_DiskRemoved;
			switcherRecordAVMonitor.StatusUpdated -= SwitcherRecordAVMonitor_StatusUpdated;
			switcherRecordAVMonitor.ErrorOccurred -= SwitcherRecordAVMonitor_ErrorOccurred;

			switcherRecordDiskMonitor.VolumeNameChanged += SwitcherRecordDiskMonitor_VolumeNameChanged;
			switcherRecordDiskMonitor.RecordingTimeAvailableChanged += SwitcherRecordDiskMonitor_RecordingTimeAvailableChanged;
			switcherRecordDiskMonitor.StatusChanged += SwitcherRecordDiskMonitor_StatusChanged;
		}

		private void TextBoxIPAddr1_PreviewTextInput(object sender, TextCompositionEventArgs e)
		{
			e.Handled = HandleIPAddressEntry(((TextBox)sender).Text + e.Text, true);
		}

		private void TextBoxIPAddr2_PreviewTextInput(object sender, TextCompositionEventArgs e)
		{
			e.Handled = HandleIPAddressEntry(((TextBox)sender).Text + e.Text, true);
		}

		private void TextBoxIPAddr3_PreviewTextInput(object sender, TextCompositionEventArgs e)
		{
			e.Handled = HandleIPAddressEntry(((TextBox)sender).Text + e.Text, true);
		}

		private void TextBoxIPAddr4_PreviewTextInput(object sender, TextCompositionEventArgs e)
		{
			if (e.Text == "\r")
			{
				e.Handled = HandleConnectEvent();
			}
			else
			{
				e.Handled = HandleIPAddressEntry(((TextBox)sender).Text + e.Text, false);
			}
		}

		private void BorderIPAddr_MouseEnter(object sender, MouseEventArgs e)
		{
			borderIPAddr.BorderBrush = new SolidColorBrush(Color.FromArgb(255, 126, 180, 234)); ;
		}

		private void BorderIPAddr_MouseLeave(object sender, MouseEventArgs e)
		{
			borderIPAddr.BorderBrush = new SolidColorBrush(Color.FromArgb(255, 171, 173, 179)); ;
		}

		private void ButtonConnect_Click(object sender, RoutedEventArgs e)
		{
			if (switcherRecordAVDevice == null)
			{
				HandleConnectEvent();
			}
			else
			{
				HandleDisconnectEvent();
			}
		}

		private void TextBoxFileBasename_LostFocus(object sender, RoutedEventArgs e)
		{
			DispatchInMainWindow(() => { switcherRecordAVDevice.RecordingFilename = textBoxFileBasename.Text; });
		}

		private void CheckBoxISORecording_Click(object sender, RoutedEventArgs e)
		{
			switcherRecordAVDevice.RecordAllISOInputs = checkBoxISORecording.IsChecked ?? false;
		}

		private void CheckBoxRecordInAllCameras_Click(object sender, RoutedEventArgs e)
		{
			switcherRecordAVDevice.RecordInAllCameras = checkBoxRecordInAllCameras.IsChecked ?? false;
		}

		private void ComboBoxDisk1_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (comboBoxDisk1.SelectedValue != null)
				switcherRecordAVDevice.Disk1WorkingSet = (uint)comboBoxDisk1.SelectedValue;
		}

		private void ComboBoxDisk2_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (comboBoxDisk2.SelectedValue != null)
				switcherRecordAVDevice.Disk2WorkingSet = (uint)comboBoxDisk2.SelectedValue;
		}

		private void ButtonStartStopRecording_Click(object sender, RoutedEventArgs e)
		{
			if (switcherRecordAVDevice == null)
				return;

			if (switcherRecordAVDevice.IsRecording)
				switcherRecordAVDevice.StopRecording();
			else
				switcherRecordAVDevice.StartRecording();
		}

		private void ButtonSwitchDisk_Click(object sender, RoutedEventArgs e)
		{
			switcherRecordAVDevice.SwitchDisk();
		}
		#endregion
	}
}
