/* -LICENSE-START-
** Copyright (c) 2021 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

using System;
using BMDSwitcherAPI;

namespace SwitcherRecordCSharp
{
	#region eventargs
	public class RecordDiskEventArgs : EventArgs
	{
		public RecordDiskEventArgs(uint diskID) => DiskID = diskID;
		public uint DiskID { get; private set; }
	}
	#endregion

	class SwitcherRecordDiskMonitor : IBMDSwitcherRecordDiskCallback
	{
		public event EventHandler<RecordDiskEventArgs> StatusChanged;
		public event EventHandler<RecordDiskEventArgs> VolumeNameChanged;
		public event EventHandler<RecordDiskEventArgs> RecordingTimeAvailableChanged;

		public SwitcherRecordDiskMonitor()
		{
		}

		void IBMDSwitcherRecordDiskCallback.Notify(_BMDSwitcherRecordDiskEventType eventType, uint diskId)
		{
			switch (eventType)
			{
				case _BMDSwitcherRecordDiskEventType.bmdSwitcherRecordDiskEventTypeStatusChanged:
					StatusChanged?.Invoke(this, new RecordDiskEventArgs(diskId));
					break;

				case _BMDSwitcherRecordDiskEventType.bmdSwitcherRecordDiskEventTypeVolumeNameChanged:
					VolumeNameChanged?.Invoke(this, new RecordDiskEventArgs(diskId));
					break;

				case _BMDSwitcherRecordDiskEventType.bmdSwitcherRecordDiskEventTypeRecordingTimeAvailableChanged:
					RecordingTimeAvailableChanged?.Invoke(this, new RecordDiskEventArgs(diskId));
					break;
			}
		}
	}
}
