/* -LICENSE-START-
** Copyright (c) 2021 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

using System;
using System.Collections.Generic;
using BMDSwitcherAPI;

namespace SwitcherRecordCSharp
{
	#region eventargs
	public class WorkingSetEventArgs : EventArgs
	{
		public WorkingSetEventArgs(uint workingSetIndex, uint diskId)
		{
			WorkingSetIndex = workingSetIndex;
			DiskId = diskId;
		}
		public uint WorkingSetIndex { get; private set; }
		public uint DiskId { get; private set; }
	}

	public class DiskAvailabilityEventArgs : EventArgs
	{
		public DiskAvailabilityEventArgs(uint diskId) => DiskID = diskId;
		public uint DiskID { get; private set; }
	}

	public class StatusUpdatedEventArgs : EventArgs
	{
		public StatusUpdatedEventArgs(_BMDSwitcherRecordAVState stateType) => StateType = stateType;
		public _BMDSwitcherRecordAVState StateType { get; private set; }
	}

	public class RecordingErrorEventArgs : EventArgs
	{
		public RecordingErrorEventArgs(string error) => Error = error;
		public string Error { get; private set; }
	}
	#endregion

	class SwitcherRecordAVMonitor : IBMDSwitcherRecordAVCallback
	{
		private readonly IReadOnlyDictionary<_BMDSwitcherRecordAVError, string> RecordErrorString = new Dictionary<_BMDSwitcherRecordAVError, string>()
		{
			{ _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorNone,               "No error" },
			{ _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorNoMedia,            "Invalid disk" },
			{ _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorMediaFull,          "No space available on disk" },
			{ _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorMediaError,         "Media error" },
			{ _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorMediaUnformatted,   "Disk is not formatted" },
			{ _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorDroppingFrames,     "Frames dropped while recording" },
			{ _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorUnknown,            "Unknown error" },
		};

		public event EventHandler RecordAllISOInputsChanged;
		public event EventHandler RecordInAllCamerasChanged;
		public event EventHandler DurationChanged;
		public event EventHandler ActiveDiskIndexChanged;
		public event EventHandler TimecodeChanged;
		public event EventHandler FilenameChanged;
		public event EventHandler TotalRecordingTimeAvailableChanged;

		public event EventHandler<WorkingSetEventArgs> WorkingSetChanged;

		public event EventHandler<DiskAvailabilityEventArgs> DiskAvailable;
		public event EventHandler<DiskAvailabilityEventArgs> DiskRemoved;

		public event EventHandler<StatusUpdatedEventArgs> StatusUpdated;
		public event EventHandler<RecordingErrorEventArgs> ErrorOccurred;

		public SwitcherRecordAVMonitor()
		{
		}

		void IBMDSwitcherRecordAVCallback.Notify(_BMDSwitcherRecordAVEventType eventType)
		{
			switch (eventType)
			{
				case _BMDSwitcherRecordAVEventType.bmdSwitcherRecordAVEventTypeRecordAllISOInputsChanged:
					RecordAllISOInputsChanged?.Invoke(this, EventArgs.Empty);
					break;

				case _BMDSwitcherRecordAVEventType.bmdSwitcherRecordAVEventTypeRecordInAllCamerasChanged:
					RecordInAllCamerasChanged?.Invoke(this, EventArgs.Empty);
					break;

				case _BMDSwitcherRecordAVEventType.bmdSwitcherRecordAVEventTypeDurationChanged:
					DurationChanged?.Invoke(this, EventArgs.Empty);
					break;

				case _BMDSwitcherRecordAVEventType.bmdSwitcherRecordAVEventTypeActiveDiskIndexChanged:
					ActiveDiskIndexChanged?.Invoke(this, EventArgs.Empty);
					break;

				case _BMDSwitcherRecordAVEventType.bmdSwitcherRecordAVEventTypeTimecodeChanged:
					TimecodeChanged?.Invoke(this, EventArgs.Empty);
					break;

				case _BMDSwitcherRecordAVEventType.bmdSwitcherRecordAVEventTypeFilenameChanged:
					FilenameChanged?.Invoke(this, EventArgs.Empty);
					break;

				case _BMDSwitcherRecordAVEventType.bmdSwitcherRecordAVEventTypeTotalRecordingTimeAvailableChanged:
					TotalRecordingTimeAvailableChanged?.Invoke(this, EventArgs.Empty);
					break;
			}
		}

		void IBMDSwitcherRecordAVCallback.NotifyWorkingSetChange(uint workingSetIndex, uint diskId)
		{
			WorkingSetChanged?.Invoke(this, new WorkingSetEventArgs(workingSetIndex, diskId));
		}

		void IBMDSwitcherRecordAVCallback.NotifyDiskAvailability(_BMDSwitcherRecordDiskAvailabilityEventType eventType, uint diskId)
		{
			switch (eventType)
			{
				case _BMDSwitcherRecordDiskAvailabilityEventType.bmdSwitcherRecordDiskAvailabilityEventTypeAvailable:
					DiskAvailable?.Invoke(this, new DiskAvailabilityEventArgs(diskId));
					break;

				case _BMDSwitcherRecordDiskAvailabilityEventType.bmdSwitcherRecordDiskAvailabilityEventTypeRemoved:
					DiskRemoved?.Invoke(this, new DiskAvailabilityEventArgs(diskId));
					break;
			}
		}

		void IBMDSwitcherRecordAVCallback.NotifyStatus(_BMDSwitcherRecordAVState stateType, _BMDSwitcherRecordAVError error)
		{
			if (error == _BMDSwitcherRecordAVError.bmdSwitcherRecordAVErrorNone)
			{
				// No error, notify status updated
				StatusUpdated?.Invoke(this, new StatusUpdatedEventArgs(stateType));
			}
			else
			{
				// Report error as string
				ErrorOccurred?.Invoke(this, new RecordingErrorEventArgs(RecordErrorString.TryGetValue(error, out string value) ? value : "Unknown error"));
			}
		}
	}
}
