import { test, expect } from '@playwright/test';
import { waitForHydration } from './helpers/wait-for-hydration';

test.describe('Filtering', () => {
  test('search input reduces visible row count', async ({ page }) => {
    await page.goto('/');
    await waitForHydration(page);

    const initialCount = await page.locator('.mh-row-header').count();
    expect(initialCount).toBeGreaterThan(0);

    const searchInput = page.locator('input[placeholder*="Filter"]');
    await searchInput.fill('Output 1');
    await page.waitForTimeout(300);

    const filteredCount = await page.locator('.mh-row-header').count();
    expect(filteredCount).toBeLessThan(initialCount);
  });

  test('clearing search restores row count', async ({ page }) => {
    await page.goto('/');
    await waitForHydration(page);

    const initialCount = await page.locator('.mh-row-header').count();

    const searchInput = page.locator('input[placeholder*="Filter"]');
    await searchInput.fill('Output 1');
    await page.waitForTimeout(300);

    await searchInput.fill('');
    await page.waitForTimeout(300);

    const restoredCount = await page.locator('.mh-row-header').count();
    expect(restoredCount).toBe(initialCount);
  });

  test('output group filter toggles active state', async ({ page }) => {
    await page.goto('/');
    await waitForHydration(page);

    // Click the first output group item — it should become active
    const firstGroupItem = page.locator('.mh-sidebar .mh-group-item').first();
    await expect(firstGroupItem).not.toHaveClass(/active/);
    await firstGroupItem.click();
    await page.waitForTimeout(300);

    await expect(firstGroupItem).toHaveClass(/active/);
  });

  test('CLEAR button appears after output group selection', async ({ page }) => {
    await page.goto('/');
    await waitForHydration(page);

    // Click the first output group item to activate a filter
    const firstGroupItem = page.locator('.mh-sidebar .mh-group-item').first();
    await firstGroupItem.click();
    await page.waitForTimeout(300);

    // The CLEAR button appears in the Output Groups section header when groups are active.
    // It uses inline style color: var(--mh-danger) and has the text "CLEAR".
    const clearButton = page.locator('.mh-sidebar button').filter({ hasText: 'CLEAR' }).first();
    await expect(clearButton).toBeVisible();
  });

  test('input group filter toggles active state', async ({ page }) => {
    await page.goto('/');
    await waitForHydration(page);

    // Input groups are under the "Auto Generated" collapsible section.
    // Click "Auto Generated" to expand if needed, then click the first sub-item.
    const autoGeneratedItem = page.locator('.mh-sidebar .mh-group-item').filter({ hasText: 'Auto Generated' });

    if (await autoGeneratedItem.count() > 0) {
      // Check if already expanded
      const childItems = page.locator('.mh-sidebar .mh-group-item[style*="padding-left"]');
      if (await childItems.count() === 0) {
        await autoGeneratedItem.first().click();
        await page.waitForTimeout(200);
      }
      const firstInputGroup = page.locator('.mh-sidebar .mh-group-item[style*="padding-left"]').first();
      await expect(firstInputGroup).not.toHaveClass(/active/);
      await firstInputGroup.click();
      await page.waitForTimeout(300);
      await expect(firstInputGroup).toHaveClass(/active/);
    } else {
      // Fallback: use the last group item in the sidebar (input group section)
      const lastItem = page.locator('.mh-sidebar .mh-group-item').last();
      await expect(lastItem).not.toHaveClass(/active/);
      await lastItem.click();
      await page.waitForTimeout(300);
      await expect(lastItem).toHaveClass(/active/);
    }
  });
});
