/* -LICENSE-START-
** Copyright (c) 2024 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
**
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

#pragma once

#ifndef BMD_CONST
	#if defined(_MSC_VER)
		#define BMD_CONST __declspec(selectany) static const
	#else
		#define BMD_CONST static const
	#endif
#endif

#include "BMDSwitcherAPI.h"

BMD_CONST REFIID IID_IBMDSwitcherMultiView_v9_4                        = /* A2581EF7-052C-460F-8981-3A14B287B120 */ { 0xA2,0x58,0x1E,0xF7,0x05,0x2C,0x46,0x0F,0x89,0x81,0x3A,0x14,0xB2,0x87,0xB1,0x20 };
BMD_CONST REFIID IID_IBMDSwitcherMultiViewIterator_v9_4                = /* CB419904-5CC0-471C-B142-D398114F568E */ { 0xCB,0x41,0x99,0x04,0x5C,0xC0,0x47,0x1C,0xB1,0x42,0xD3,0x98,0x11,0x4F,0x56,0x8E };

#if defined(__cplusplus)

// Forward Declarations
class IBMDSwitcherMultiView_v9_4;
class IBMDSwitcherMultiViewIterator_v9_4;

/* Interface IBMDSwitcherMultiView_v9_4 - MultiView Object */

class BMD_PUBLIC IBMDSwitcherMultiView_v9_4 : public IUnknown
{
public:
    virtual HRESULT CanChangeLayout (/* out */ bool* canChangeLayout) = 0;
    virtual HRESULT GetLayout (/* out */ BMDSwitcherMultiViewLayout* layout) = 0;
    virtual HRESULT SetLayout (/* in */ BMDSwitcherMultiViewLayout layout) = 0;
    virtual HRESULT SupportsQuadrantLayout (/* out */ bool* supportsQuadrantLayout) = 0;
    virtual HRESULT GetWindowInput (/* in */ uint32_t window, /* out */ BMDSwitcherInputId* input) = 0;
    virtual HRESULT SetWindowInput (/* in */ uint32_t window, /* in */ BMDSwitcherInputId input) = 0;
    virtual HRESULT GetWindowCount (/* out */ uint32_t* windowCount) = 0;
    virtual HRESULT GetInputAvailabilityMask (/* out */ BMDSwitcherInputAvailability* availabilityMask) = 0;
    virtual HRESULT CanRouteInputs (/* out */ bool* canRoute) = 0;
    virtual HRESULT SupportsVuMeters (/* out */ bool* supportsVuMeters) = 0;
    virtual HRESULT CurrentInputSupportsVuMeter (/* in */ uint32_t window, /* out */ bool* supportsVuMeter) = 0;
    virtual HRESULT GetVuMeterEnabled (/* in */ uint32_t window, /* out */ bool* enabled) = 0;
    virtual HRESULT SetVuMeterEnabled (/* in */ uint32_t window, /* in */ bool enabled) = 0;
    virtual HRESULT CanAdjustVuMeterOpacity (/* out */ bool* canAdjustVuMeterOpacity) = 0;
    virtual HRESULT GetVuMeterOpacity (/* out */ double* opacity) = 0;
    virtual HRESULT SetVuMeterOpacity (/* in */ double opacity) = 0;
    virtual HRESULT CanToggleSafeAreaEnabled (/* out */ bool* canToggleSafeAreaEnabled) = 0;
    virtual HRESULT CurrentInputSupportsSafeArea (/* in */ uint32_t window, /* out */ bool* supportsSafeArea) = 0;
    virtual HRESULT GetSafeAreaEnabled (/* in */ uint32_t window, /* out */ bool* enabled) = 0;
    virtual HRESULT SetSafeAreaEnabled (/* in */ uint32_t window, /* in */ bool enabled) = 0;
    virtual HRESULT GetSupportedSafeAreaTypes (/* out */ uint32_t* supportedSafeAreaTypeFlags) = 0;
    virtual HRESULT GetSafeAreaType (/* in */ uint32_t window, /* out */ BMDSwitcherMultiViewSafeAreaType* type) = 0;
    virtual HRESULT SetSafeAreaType (/* in */ uint32_t window, /* in */ BMDSwitcherMultiViewSafeAreaType type) = 0;
    virtual HRESULT SupportsProgramPreviewSwap (/* out */ bool* supportsProgramPreviewSwap) = 0;
    virtual HRESULT GetProgramPreviewSwapped (/* out */ bool* swapped) = 0;
    virtual HRESULT SetProgramPreviewSwapped (/* in */ bool swapped) = 0;
    virtual HRESULT CanChangeOverlayProperties (/* out */ bool* canChangeOverlay) = 0;
    virtual HRESULT GetLabelVisible (/* in */ uint32_t window, /* out */ bool* visible) = 0;
    virtual HRESULT SetLabelVisible (/* in */ uint32_t window, /* in */ bool visible) = 0;
    virtual HRESULT GetBorderVisible (/* in */ uint32_t window, /* out */ bool* visible) = 0;
    virtual HRESULT SetBorderVisible (/* in */ uint32_t window, /* in */ bool visible) = 0;
    virtual HRESULT GetBorderColor (/* out */ double* red, /* out */ double* green, /* out */ double* blue, /* out */ double* alpha) = 0;
    virtual HRESULT SetBorderColor (/* in */ double red, /* in */ double green, /* in */ double blue, /* in */ double alpha) = 0;
    virtual HRESULT AddCallback (/* in */ IBMDSwitcherMultiViewCallback* callback) = 0;
    virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherMultiViewCallback* callback) = 0;

protected:
    virtual ~IBMDSwitcherMultiView_v9_4() {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherMultiViewIterator_v9_4 - MultiView Iterator */

class BMD_PUBLIC IBMDSwitcherMultiViewIterator_v9_4 : public IUnknown
{
public:
    virtual HRESULT Next (/* out */ IBMDSwitcherMultiView_v9_4** multiView) = 0;

protected:
    virtual ~IBMDSwitcherMultiViewIterator_v9_4 () {} // call Release method to drop reference count
};

#endif      // defined(__cplusplus)
