/* -LICENSE-START-
 ** Copyright (c) 2025 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#ifndef BMD_BMDSWITCHERAPI_V9_8_3_H
#define BMD_BMDSWITCHERAPI_V9_8_3_H


#ifndef BMD_CONST
    #if defined(_MSC_VER)
        #define BMD_CONST __declspec(selectany) static const
    #else
        #define BMD_CONST static const
    #endif
#endif

#include "BMDSwitcherAPI.h"

BMD_CONST REFIID IID_IBMDSwitcher_v9_8_3                       = /* 5054C164-9E2A-40EF-AC22-6D07341D0ECC */ { 0x50,0x54,0xC1,0x64,0x9E,0x2A,0x40,0xEF,0xAC,0x22,0x6D,0x07,0x34,0x1D,0x0E,0xCC };
BMD_CONST REFIID IID_IBMDSwitcherDiscovery_v9_8_3              = /* 83C30ED4-4314-4C81-B1E3-23C518D6D8BD */ { 0x83,0xC3,0x0E,0xD4,0x43,0x14,0x4C,0x81,0xB1,0xE3,0x23,0xC5,0x18,0xD6,0xD8,0xBD };
BMD_CONST REFIID IID_IBMDSwitcherMixEffectBlock_v9_8_3         = /* 6604B7AD-A814-46B2-8C69-C1C38815419A */ { 0x66,0x04,0xB7,0xAD,0xA8,0x14,0x46,0xB2,0x8C,0x69,0xC1,0xC3,0x88,0x15,0x41,0x9A };
BMD_CONST REFIID IID_IBMDSwitcherMixEffectBlockIterator_v9_8_3 = /* EA8D1E06-4A59-47EF-AF68-C7F074A35FE9 */ { 0xEA,0x8D,0x1E,0x06,0x4A,0x59,0x47,0xEF,0xAF,0x68,0xC7,0xF0,0x74,0xA3,0x5F,0xE9 };
BMD_CONST REFIID IID_IBMDSwitcherInputAux_v9_8_3               = /* 52C745A8-89B1-449A-A149-C43F5108DAE7 */ { 0x52,0xC7,0x45,0xA8,0x89,0xB1,0x44,0x9A,0xA1,0x49,0xC4,0x3F,0x51,0x08,0xDA,0xE7 };


#if defined(__cplusplus)

// Forward Declarations

class IBMDSwitcher_v9_8_3;
class IBMDSwitcherDiscovery_v9_8_3;
class IBMDSwitcherMixEffectBlock_v9_8_3;

/* Interface IBMDSwitcher_v9_8_3 - Switcher Object */

class BMD_PUBLIC IBMDSwitcher_v9_8_3 : public IUnknown
{
public:
	virtual HRESULT GetProductName (/* out */ CFStringRef* productName) = 0;
	virtual HRESULT GetVideoMode (/* out */ BMDSwitcherVideoMode* videoMode) = 0;
	virtual HRESULT SetVideoMode (/* in */ BMDSwitcherVideoMode videoMode) = 0;
	virtual HRESULT DoesSupportVideoMode (/* in */ BMDSwitcherVideoMode videoMode, /* out */ bool* supported) = 0;
	virtual HRESULT DoesVideoModeChangeRequireReconfiguration (/* in */ BMDSwitcherVideoMode videoMode, /* out */ bool* required) = 0;
	virtual HRESULT GetMethodForDownConvertedSD (/* out */ BMDSwitcherDownConversionMethod* method) = 0;
	virtual HRESULT SetMethodForDownConvertedSD (/* in */ BMDSwitcherDownConversionMethod method) = 0;
	virtual HRESULT GetDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* out */ BMDSwitcherVideoMode* downConvertedHDVideoMode) = 0;
	virtual HRESULT SetDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode downConvertedHDVideoMode) = 0;
	virtual HRESULT DoesSupportDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode downConvertedHDVideoMode, /* out */ bool* supported) = 0;
	virtual HRESULT GetMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* out */ BMDSwitcherVideoMode* multiviewVideoMode) = 0;
	virtual HRESULT SetMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode multiviewVideoMode) = 0;
	virtual HRESULT DoesSupportMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode multiviewVideoMode, /* out */ bool* supported) = 0;
	virtual HRESULT Get3GSDIOutputLevel (/* out */ BMDSwitcher3GSDIOutputLevel* outputLevel) = 0;
	virtual HRESULT Set3GSDIOutputLevel (/* in */ BMDSwitcher3GSDIOutputLevel outputLevel) = 0;
	virtual HRESULT DoesSupportColorimetrySetting (/* out */ bool* supported) = 0;
	virtual HRESULT GetColorimetryMode (/* out */ BMDSwitcherColorimetryMode* colorimetry) = 0;
	virtual HRESULT SetColorimetryMode (/* in */ BMDSwitcherColorimetryMode colorimetry) = 0;
	virtual HRESULT GetPowerStatus (/* out */ BMDSwitcherPowerStatus* powerStatus) = 0;
	virtual HRESULT GetTimeCode (/* out */ uint8_t* hours, /* out */ uint8_t* minutes, /* out */ uint8_t* seconds, /* out */ uint8_t* frames, /* out */ bool* dropFrame) = 0;
	virtual HRESULT SetTimeCode (/* in */ uint8_t hours, /* in */ uint8_t minutes, /* in */ uint8_t seconds, /* in */ uint8_t frames) = 0;
	virtual HRESULT RequestTimeCode (void) = 0;
	virtual HRESULT GetTimeCodeLocked (/* out */ bool* timeCodeLocked) = 0;
	virtual HRESULT GetTimeCodeExternal (/* out */ bool* timeCodeExternal) = 0;
	virtual HRESULT GetTimeCodeMode (/* out */ BMDSwitcherTimeCodeMode* timeCodeMode) = 0;
	virtual HRESULT SetTimeCodeMode (/* in */ BMDSwitcherTimeCodeMode timeCodeMode) = 0;
	virtual HRESULT GetAreOutputsConfigurable (/* out */ bool* configurable) = 0;
	virtual HRESULT GetSuperSourceCascade (/* out */ bool* cascade) = 0;
	virtual HRESULT SetSuperSourceCascade (/* in */ bool cascade) = 0;
	virtual HRESULT SuspendStreaming (/* in */ uint32_t durationMs) = 0;
	virtual HRESULT AllowStreamingToResume (void) = 0;
	virtual HRESULT DoesSupportAutoVideoMode (/* out */ bool* supported) = 0;
	virtual HRESULT GetAutoVideoMode (/* out */ bool* enabled) = 0;
	virtual HRESULT GetAutoVideoModeDetected (/* out */ bool* detected) = 0;
	virtual HRESULT SetAutoVideoMode (/* in */ bool enabled) = 0;
	virtual HRESULT DoesSupportFadeToBlackEnabledSetting (/* out */ bool* supported) = 0;
	virtual HRESULT GetFadeToBlackEnabled (/* out */ bool* enabled) = 0;
	virtual HRESULT SetFadeToBlackEnabled (/* in */ bool enabled) = 0;
	virtual HRESULT DoesSupportDskTallyOverride (/* out */ bool* supported) = 0;
	virtual HRESULT GetDskTallyOverrideEnabled (/* out */ bool* enabled) = 0;
	virtual HRESULT SetDskTallyOverrideEnabled (/* in */ bool enabled) = 0;
	virtual HRESULT CreateIterator (/* in */ REFIID iid, /* out */ LPVOID* ppv) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherCallback* callback) = 0;

protected:
	virtual ~IBMDSwitcher_v9_8_3 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherDiscovery_v9_8_3 - Used to discover and connect to switchers */

class BMD_PUBLIC IBMDSwitcherDiscovery_v9_8_3 : public IUnknown
{
public:
	virtual HRESULT ConnectTo (/* in */ CFStringRef deviceAddress, /* out */ IBMDSwitcher_v9_8_3** switcherDevice, /* out */ BMDSwitcherConnectToFailure* failReason) = 0;
protected:
	virtual ~IBMDSwitcherDiscovery_v9_8_3 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherMixEffectBlock_v9_8_3 - Mix Effect Block */

class BMD_PUBLIC IBMDSwitcherMixEffectBlock_v9_8_3 : public IUnknown
{
public:
	virtual HRESULT GetProgramInput (/* out */ BMDSwitcherInputId* value) = 0;
	virtual HRESULT SetProgramInput (/* in */ BMDSwitcherInputId value) = 0;
	virtual HRESULT GetPreviewInput (/* out */ BMDSwitcherInputId* value) = 0;
	virtual HRESULT SetPreviewInput (/* in */ BMDSwitcherInputId value) = 0;
	virtual HRESULT GetPreviewLive (/* out */ bool* value) = 0;
	virtual HRESULT GetPreviewTransition (/* out */ bool* value) = 0;
	virtual HRESULT SetPreviewTransition (/* in */ bool value) = 0;
	virtual HRESULT PerformAutoTransition (void) = 0;
	virtual HRESULT PerformCut (void) = 0;
	virtual HRESULT GetInTransition (/* out */ bool* value) = 0;
	virtual HRESULT GetTransitionPosition (/* out */ double* value) = 0;
	virtual HRESULT SetTransitionPosition (/* in */ double value) = 0;
	virtual HRESULT GetTransitionFramesRemaining (/* out */ uint32_t* value) = 0;
	virtual HRESULT PerformFadeToBlack (void) = 0;
	virtual HRESULT GetFadeToBlackRate (/* out */ uint32_t* value) = 0;
	virtual HRESULT SetFadeToBlackRate (/* in */ uint32_t value) = 0;
	virtual HRESULT GetFadeToBlackFramesRemaining (/* out */ uint32_t* value) = 0;
	virtual HRESULT GetFadeToBlackFullyBlack (/* out */ bool* value) = 0;
	virtual HRESULT SetFadeToBlackFullyBlack (/* in */ bool value) = 0;
	virtual HRESULT GetInFadeToBlack (/* out */ bool* value) = 0;
	virtual HRESULT GetFadeToBlackInTransition (/* out */ bool* value) = 0;
	virtual HRESULT GetInputAvailabilityMask (/* out */ BMDSwitcherInputAvailability* value) = 0;
	virtual HRESULT CreateIterator (/* in */ REFIID iid, /* out */ LPVOID* ppv) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherMixEffectBlockCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherMixEffectBlockCallback* callback) = 0;

protected:
	virtual ~IBMDSwitcherMixEffectBlock_v9_8_3 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherMixEffectBlockIterator - Mix Effect Block Iterator */

class BMD_PUBLIC IBMDSwitcherMixEffectBlockIterator_v9_8_3 : public IUnknown
{
public:
	virtual HRESULT Next (/* out */ IBMDSwitcherMixEffectBlock_v9_8_3** mixEffectBlock) = 0;

protected:
	virtual ~IBMDSwitcherMixEffectBlockIterator_v9_8_3 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherInputAux - Aux Input Object */

class BMD_PUBLIC IBMDSwitcherInputAux_v9_8_3 : public IUnknown
{
public:
	virtual HRESULT GetInputSource (/* out */ BMDSwitcherInputId* input) = 0;
	virtual HRESULT SetInputSource (/* in */ BMDSwitcherInputId input) = 0;
	virtual HRESULT GetInputAvailabilityMask (/* out */ BMDSwitcherInputAvailability* availabilityMask) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherInputAuxCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherInputAuxCallback* callback) = 0;

protected:
	virtual ~IBMDSwitcherInputAux_v9_8_3 () {} // call Release method to drop reference count
};


#endif // defined(__cplusplus)
#endif /* defined(BMD_BMDSWITCHERAPI_V9_8_3_H) */
