/* -LICENSE-START-
** Copyright (c) 2024 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
**
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

#pragma once

// #ifndef BMD_CONST
//     #if defined(_MSC_VER)
//         #define BMD_CONST __declspec(selectany) static const
//     #else
//         #define BMD_CONST static const
//     #endif
// #endif

#include "BMDSwitcherAPI.h"

BMD_CONST REFIID IID_IBMDSwitcherInput_v9_6_1                      = /* E2B5A31D-95A9-421E-A805-F73ACDC1364A */ { 0xE2,0xB5,0xA3,0x1D,0x95,0xA9,0x42,0x1E,0xA8,0x05,0xF7,0x3A,0xCD,0xC1,0x36,0x4A };
BMD_CONST REFIID IID_IBMDSwitcherInputIterator_v9_6_1              = /* 5EA5F512-4E54-4595-9853-BA1FCA71CDAF */ { 0x5E,0xA5,0xF5,0x12,0x4E,0x54,0x45,0x95,0x98,0x53,0xBA,0x1F,0xCA,0x71,0xCD,0xAF };
BMD_CONST REFIID IID_IBMDSwitcherSerialPort_v9_6_1                 = /* 14BEA77D-3F69-4FBF-A331-F5EA9FF6A42E */ { 0x14,0xBE,0xA7,0x7D,0x3F,0x69,0x4F,0xBF,0xA3,0x31,0xF5,0xEA,0x9F,0xF6,0xA4,0x2E };
BMD_CONST REFIID IID_IBMDSwitcherSerialPortIterator_v9_6_1         = /* E3F0E3CE-5A1A-4D60-94A4-D3DBB2514763 */ { 0xE3,0xF0,0xE3,0xCE,0x5A,0x1A,0x4D,0x60,0x94,0xA4,0xD3,0xDB,0xB2,0x51,0x47,0x63 };

#if defined(__cplusplus)

// Forward Declarations
class IBMDSwitcherInput_v9_6_1;
class IBMDSwitcherInputIterator_v9_6_1;
class IBMDSwitcherSerialPortIterator_v9_6_1;
class IBMDSwitcherSerialPort_v9_6_1;

/* Interface IBMDSwitcherInput_v9_6_1 - Switcher Input Object */

class BMD_PUBLIC IBMDSwitcherInput_v9_6_1 : public IUnknown
{
public:
    virtual HRESULT GetPortType (/* out */ BMDSwitcherPortType* type) = 0;
    virtual HRESULT GetInputAvailability (/* out */ BMDSwitcherInputAvailability* availability) = 0;
    virtual HRESULT SetShortName (/* in */ CFStringRef name) = 0;
    virtual HRESULT GetShortName (/* out */ CFStringRef* name) = 0;
    virtual HRESULT SetLongName (/* in */ CFStringRef name) = 0;
    virtual HRESULT GetLongName (/* out */ CFStringRef* name) = 0;
    virtual HRESULT AreNamesDefault (/* out */ bool* isDefault) = 0;
    virtual HRESULT ResetNames (void) = 0;
    virtual HRESULT IsProgramTallied (/* out */ bool* isTallied) = 0;
    virtual HRESULT IsPreviewTallied (/* out */ bool* isTallied) = 0;
    virtual HRESULT GetAvailableExternalPortTypes (/* out */ BMDSwitcherExternalPortType* types) = 0;
    virtual HRESULT SetCurrentExternalPortType (/* in */ BMDSwitcherExternalPortType value) = 0;
    virtual HRESULT GetCurrentExternalPortType (/* out */ BMDSwitcherExternalPortType* value) = 0;
    virtual HRESULT SetCameraModel (/* in */ uint32_t cameraId) = 0;
    virtual HRESULT GetCameraModel (/* out */ uint32_t* cameraId) = 0;
    virtual HRESULT DoesSupportCameraModel (/* out */ bool* doesSupportCameraModel) = 0;
    virtual HRESULT GetInputId (/* out */ BMDSwitcherInputId* inputId) = 0;
    virtual HRESULT AddCallback (/* in */ IBMDSwitcherInputCallback* callback) = 0;
    virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherInputCallback* callback) = 0;

protected:
    virtual ~IBMDSwitcherInput_v9_6_1 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherInputIterator_v9_6_1 - Input Iterator */

class BMD_PUBLIC IBMDSwitcherInputIterator_v9_6_1 : public IUnknown
{
public:
    virtual HRESULT Next (/* out */ IBMDSwitcherInput_v9_6_1** input) = 0;
    virtual HRESULT GetById (/* in */ BMDSwitcherInputId inputId, /* out */ IBMDSwitcherInput_v9_6_1** input) = 0;

protected:
    virtual ~IBMDSwitcherInputIterator_v9_6_1 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherSerialPort_v9_6_1 - Serial Port */

class BMD_PUBLIC IBMDSwitcherSerialPort_v9_6_1 : public IUnknown
{
public:
    virtual HRESULT SetFunction (/* in */ BMDSwitcherSerialPortFunction function) = 0;
    virtual HRESULT GetFunction (/* out */ BMDSwitcherSerialPortFunction* function) = 0;
    virtual HRESULT DoesSupportFunction (/* in */ BMDSwitcherSerialPortFunction function, /* out */ bool* supported) = 0;
    virtual HRESULT AddCallback (/* in */ IBMDSwitcherSerialPortCallback* callback) = 0;
    virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherSerialPortCallback* callback) = 0;

protected:
    virtual ~IBMDSwitcherSerialPort_v9_6_1 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherSerialPortIterator_v9_6_1 - Serial Port Iterator */

class BMD_PUBLIC IBMDSwitcherSerialPortIterator_v9_6_1 : public IUnknown
{
public:
    virtual HRESULT Next (/* out */ IBMDSwitcherSerialPort_v9_6_1** serialPort) = 0;

protected:
    virtual ~IBMDSwitcherSerialPortIterator_v9_6_1 () {} // call Release method to drop reference count
};

#endif /* defined(__cplusplus) */
