/* -LICENSE-START-
 ** Copyright (c) 2025 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#ifndef BMD_BMDSWITCHERAPI_V10_0_H
#define BMD_BMDSWITCHERAPI_V10_0_H


#ifndef BMD_CONST
    #if defined(_MSC_VER)
        #define BMD_CONST __declspec(selectany) static const
    #else
        #define BMD_CONST static const
    #endif
#endif

#include "BMDSwitcherAPI.h"

BMD_CONST REFIID IID_IBMDSwitcherFairlightAnalogAudioInput_v10_0 = /* 7103C039-96F5-46C0-B2AF-A7FFFFFBB4F2 */ { 0x71,0x03,0xC0,0x39,0x96,0xF5,0x46,0xC0,0xB2,0xAF,0xA7,0xFF,0xFF,0xFB,0xB4,0xF2 };


#if defined(__cplusplus)

// Forward Declarations

class IBMDSwitcherFairlightAnalogAudioInput_v10_0;

/* Interface IBMDSwitcherFairlightAnalogAudioInput_v10_0 - Fairlight Analog Audio Input Object */

class BMD_PUBLIC IBMDSwitcherFairlightAnalogAudioInput_v10_0 : public IUnknown
{
public:
	virtual HRESULT GetSupportedInputLevels (/* out */ BMDSwitcherFairlightAudioAnalogInputLevel* levels) = 0;
	virtual HRESULT GetInputLevel (/* out */ BMDSwitcherFairlightAudioAnalogInputLevel* level) = 0;
	virtual HRESULT SetInputLevel (/* in */ BMDSwitcherFairlightAudioAnalogInputLevel level) = 0;
	virtual HRESULT GetSupportedMicPowerModes (/* out */ BMDSwitcherFairlightAudioAnalogInputMicPowerMode* powerModes) = 0;
	virtual HRESULT GetMicPowerMode (/* out */ BMDSwitcherFairlightAudioAnalogInputMicPowerMode* powerMode) = 0;
	virtual HRESULT SetMicPowerMode (/* in */ BMDSwitcherFairlightAudioAnalogInputMicPowerMode powerMode) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherFairlightAnalogAudioInputCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherFairlightAnalogAudioInputCallback* callback) = 0;

protected:
	virtual ~IBMDSwitcherFairlightAnalogAudioInput_v10_0 () {} // call Release method to drop reference count
};


#endif // defined(__cplusplus)
#endif /* defined(BMD_BMDSWITCHERAPI_V10_0_H) */
