/* -LICENSE-START-
 ** Copyright (c) 2025 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#ifndef BMD_BMDSWITCHERAPI_V10_1_1_H
#define BMD_BMDSWITCHERAPI_V10_1_1_H


#ifndef BMD_CONST
    #if defined(_MSC_VER)
        #define BMD_CONST __declspec(selectany) static const
    #else
        #define BMD_CONST static const
    #endif
#endif

#include "BMDSwitcherAPI.h"

BMD_CONST REFIID IID_IBMDSwitcher_v10_1_1                       = /* FD979282-9281-4FDC-8C1F-012F3FB12245 */ { 0xFD,0x97,0x92,0x82,0x92,0x81,0x4F,0xDC,0x8C,0x1F,0x01,0x2F,0x3F,0xB1,0x22,0x45 };
BMD_CONST REFIID IID_IBMDSwitcherDiscovery_v10_1_1              = /* 1EEE089A-5422-4A76-B068-F6EDCFBD3AC0 */ { 0x1E,0xEE,0x08,0x9A,0x54,0x22,0x4A,0x76,0xB0,0x68,0xF6,0xED,0xCF,0xBD,0x3A,0xC0 };


#if defined(__cplusplus)

// Forward Declarations

class IBMDSwitcher_v10_1_1;
class IBMDSwitcherDiscovery_v10_1_1;

/* Interface IBMDSwitcher_v10_1_1 - Switcher Object */

class BMD_PUBLIC IBMDSwitcher_v10_1_1 : public IUnknown
{
public:
	virtual HRESULT GetProductName (/* out */ CFStringRef* productName) = 0;
	virtual HRESULT GetVideoMode (/* out */ BMDSwitcherVideoMode* videoMode) = 0;
	virtual HRESULT SetVideoMode (/* in */ BMDSwitcherVideoMode videoMode) = 0;
	virtual HRESULT DoesSupportVideoMode (/* in */ BMDSwitcherVideoMode videoMode, /* out */ bool* supported) = 0;
	virtual HRESULT DoesVideoModeChangeRequireReconfiguration (/* in */ BMDSwitcherVideoMode videoMode, /* out */ bool* required) = 0;
	virtual HRESULT GetMethodForDownConvertedSD (/* out */ BMDSwitcherDownConversionMethod* method) = 0;
	virtual HRESULT SetMethodForDownConvertedSD (/* in */ BMDSwitcherDownConversionMethod method) = 0;
	virtual HRESULT GetDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* out */ BMDSwitcherVideoMode* downConvertedHDVideoMode) = 0;
	virtual HRESULT SetDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode downConvertedHDVideoMode) = 0;
	virtual HRESULT DoesSupportDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode downConvertedHDVideoMode, /* out */ bool* supported) = 0;
	virtual HRESULT GetMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* out */ BMDSwitcherVideoMode* multiviewVideoMode) = 0;
	virtual HRESULT SetMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode multiviewVideoMode) = 0;
	virtual HRESULT DoesSupportMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode multiviewVideoMode, /* out */ bool* supported) = 0;
	virtual HRESULT Get3GSDIOutputLevel (/* out */ BMDSwitcher3GSDIOutputLevel* outputLevel) = 0;
	virtual HRESULT Set3GSDIOutputLevel (/* in */ BMDSwitcher3GSDIOutputLevel outputLevel) = 0;
	virtual HRESULT DoesSupportColorimetrySetting (/* out */ bool* supported) = 0;
	virtual HRESULT GetColorimetryMode (/* out */ BMDSwitcherColorimetryMode* colorimetry) = 0;
	virtual HRESULT SetColorimetryMode (/* in */ BMDSwitcherColorimetryMode colorimetry) = 0;
	virtual HRESULT GetPowerStatus (/* out */ BMDSwitcherPowerStatus* powerStatus) = 0;
	virtual HRESULT GetTimeCode (/* out */ uint8_t* hours, /* out */ uint8_t* minutes, /* out */ uint8_t* seconds, /* out */ uint8_t* frames, /* out */ bool* dropFrame) = 0;
	virtual HRESULT SetTimeCode (/* in */ uint8_t hours, /* in */ uint8_t minutes, /* in */ uint8_t seconds, /* in */ uint8_t frames) = 0;
	virtual HRESULT RequestTimeCode (void) = 0;
	virtual HRESULT GetTimeCodeLocked (/* out */ bool* timeCodeLocked) = 0;
	virtual HRESULT GetTimeCodeExternal (/* out */ bool* timeCodeExternal) = 0;
	virtual HRESULT GetTimeCodeMode (/* out */ BMDSwitcherTimeCodeMode* timeCodeMode) = 0;
	virtual HRESULT SetTimeCodeMode (/* in */ BMDSwitcherTimeCodeMode timeCodeMode) = 0;
	virtual HRESULT GetAreOutputsConfigurable (/* out */ bool* configurable) = 0;
	virtual HRESULT GetSuperSourceCascade (/* out */ bool* cascade) = 0;
	virtual HRESULT SetSuperSourceCascade (/* in */ bool cascade) = 0;
	virtual HRESULT SuspendStreaming (/* in */ uint32_t durationMs) = 0;
	virtual HRESULT AllowStreamingToResume (void) = 0;
	virtual HRESULT DoesSupportAutoVideoMode (/* out */ bool* supported) = 0;
	virtual HRESULT GetAutoVideoMode (/* out */ bool* enabled) = 0;
	virtual HRESULT GetAutoVideoModeDetected (/* out */ bool* detected) = 0;
	virtual HRESULT SetAutoVideoMode (/* in */ bool enabled) = 0;
	virtual HRESULT DoesSupportFadeToBlackEnabledSetting (/* out */ bool* supported) = 0;
	virtual HRESULT GetFadeToBlackEnabled (/* out */ bool* enabled) = 0;
	virtual HRESULT SetFadeToBlackEnabled (/* in */ bool enabled) = 0;
	virtual HRESULT DoesSupportDskTallyOverride (/* out */ bool* supported) = 0;
	virtual HRESULT GetDskTallyOverrideEnabled (/* out */ bool* enabled) = 0;
	virtual HRESULT SetDskTallyOverrideEnabled (/* in */ bool enabled) = 0;
	virtual HRESULT DoesSupportTallyConfig (/* out */ bool* supported) = 0;
	virtual HRESULT CreateIterator (/* in */ REFIID iid, /* out */ LPVOID* ppv) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherCallback* callback) = 0;

protected:
	virtual ~IBMDSwitcher_v10_1_1 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherDiscovery_v10_1_1 - Used to discover and connect to switchers */

class BMD_PUBLIC IBMDSwitcherDiscovery_v10_1_1 : public IUnknown
{
public:
	virtual HRESULT ConnectTo (/* in */ CFStringRef deviceAddress, /* out */ IBMDSwitcher_v10_1_1** switcherDevice, /* out */ BMDSwitcherConnectToFailure* failReason) = 0;
protected:
	virtual ~IBMDSwitcherDiscovery_v10_1_1 () {} // call Release method to drop reference count
};


#endif // defined(__cplusplus)
#endif /* defined(BMD_BMDSWITCHERAPI_V10_1_1_H) */
