/* -LICENSE-START-
 ** Copyright (c) 2025 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#ifndef BMD_BMDSWITCHERAPI_V9_6_3_H
#define BMD_BMDSWITCHERAPI_V9_6_3_H


#ifndef BMD_CONST
    #if defined(_MSC_VER)
        #define BMD_CONST __declspec(selectany) static const
    #else
        #define BMD_CONST static const
    #endif
#endif

#include "BMDSwitcherAPI.h"

BMD_CONST REFIID IID_IBMDSwitcher_v9_6_3                    = /* 41F9EEC4-2F04-4608-A154-6A16485FDC08 */ { 0x41,0xF9,0xEE,0xC4,0x2F,0x04,0x46,0x08,0xA1,0x54,0x6A,0x16,0x48,0x5F,0xDC,0x08 };
BMD_CONST REFIID IID_IBMDSwitcherDiscovery_v9_6_3           = /* 7F10848C-A281-43B4-94F6-2E1B388600D8 */ { 0x7F,0x10,0x84,0x8C,0xA2,0x81,0x43,0xB4,0x94,0xF6,0x2E,0x1B,0x38,0x86,0x00,0xD8 };


#if defined(__cplusplus)

// Forward Declarations

class IBMDSwitcher_v9_6_3;
class IBMDSwitcherDiscovery_v9_6_3;

/* Interface IBMDSwitcher_v9_6_3 - Switcher Object */

class BMD_PUBLIC IBMDSwitcher_v9_6_3 : public IUnknown
{
public:
	virtual HRESULT GetProductName (/* out */ CFStringRef* productName) = 0;
	virtual HRESULT GetVideoMode (/* out */ BMDSwitcherVideoMode* videoMode) = 0;
	virtual HRESULT SetVideoMode (/* in */ BMDSwitcherVideoMode videoMode) = 0;
	virtual HRESULT DoesSupportVideoMode (/* in */ BMDSwitcherVideoMode videoMode, /* out */ bool* supported) = 0;
	virtual HRESULT DoesVideoModeChangeRequireReconfiguration (/* in */ BMDSwitcherVideoMode videoMode, /* out */ bool* required) = 0;
	virtual HRESULT GetMethodForDownConvertedSD (/* out */ BMDSwitcherDownConversionMethod* method) = 0;
	virtual HRESULT SetMethodForDownConvertedSD (/* in */ BMDSwitcherDownConversionMethod method) = 0;
	virtual HRESULT GetDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* out */ BMDSwitcherVideoMode* downConvertedHDVideoMode) = 0;
	virtual HRESULT SetDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode downConvertedHDVideoMode) = 0;
	virtual HRESULT DoesSupportDownConvertedHDVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode downConvertedHDVideoMode, /* out */ bool* supported) = 0;
	virtual HRESULT GetMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* out */ BMDSwitcherVideoMode* multiviewVideoMode) = 0;
	virtual HRESULT SetMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode multiviewVideoMode) = 0;
	virtual HRESULT DoesSupportMultiViewVideoMode (/* in */ BMDSwitcherVideoMode coreVideoMode, /* in */ BMDSwitcherVideoMode multiviewVideoMode, /* out */ bool* supported) = 0;
	virtual HRESULT Get3GSDIOutputLevel (/* out */ BMDSwitcher3GSDIOutputLevel* outputLevel) = 0;
	virtual HRESULT Set3GSDIOutputLevel (/* in */ BMDSwitcher3GSDIOutputLevel outputLevel) = 0;
	virtual HRESULT DoesSupportColorimetrySetting (/* out */ bool* supported) = 0;
	virtual HRESULT GetColorimetryMode (/* out */ BMDSwitcherColorimetryMode* colorimetry) = 0;
	virtual HRESULT SetColorimetryMode (/* in */ BMDSwitcherColorimetryMode colorimetry) = 0;
	virtual HRESULT GetPowerStatus (/* out */ BMDSwitcherPowerStatus* powerStatus) = 0;
	virtual HRESULT GetTimeCode (/* out */ uint8_t* hours, /* out */ uint8_t* minutes, /* out */ uint8_t* seconds, /* out */ uint8_t* frames, /* out */ bool* dropFrame) = 0;
	virtual HRESULT SetTimeCode (/* in */ uint8_t hours, /* in */ uint8_t minutes, /* in */ uint8_t seconds, /* in */ uint8_t frames) = 0;
	virtual HRESULT RequestTimeCode (void) = 0;
	virtual HRESULT GetTimeCodeLocked (/* out */ bool* timeCodeLocked) = 0;
	virtual HRESULT GetTimeCodeExternal (/* out */ bool* timeCodeExternal) = 0;
	virtual HRESULT GetTimeCodeMode (/* out */ BMDSwitcherTimeCodeMode* timeCodeMode) = 0;
	virtual HRESULT SetTimeCodeMode (/* in */ BMDSwitcherTimeCodeMode timeCodeMode) = 0;
	virtual HRESULT GetAreOutputsConfigurable (/* out */ bool* configurable) = 0;
	virtual HRESULT GetSuperSourceCascade (/* out */ bool* cascade) = 0;
	virtual HRESULT SetSuperSourceCascade (/* in */ bool cascade) = 0;
	virtual HRESULT SuspendStreaming (/* in */ uint32_t durationMs) = 0;
	virtual HRESULT AllowStreamingToResume (void) = 0;
	virtual HRESULT DoesSupportAutoVideoMode (/* out */ bool* supported) = 0;
	virtual HRESULT GetAutoVideoMode (/* out */ bool* enabled) = 0;
	virtual HRESULT GetAutoVideoModeDetected (/* out */ bool* detected) = 0;
	virtual HRESULT SetAutoVideoMode (/* in */ bool enabled) = 0;
	virtual HRESULT DoesSupportFadeToBlackEnabledSetting (/* out */ bool* supported) = 0;
	virtual HRESULT GetFadeToBlackEnabled (/* out */ bool* enabled) = 0;
	virtual HRESULT SetFadeToBlackEnabled (/* in */ bool enabled) = 0;
	virtual HRESULT CreateIterator (/* in */ REFIID iid, /* out */ LPVOID* ppv) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherCallback* callback) = 0;

protected:
	virtual ~IBMDSwitcher_v9_6_3 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherDiscovery_v9_6_3 - Used to discover and connect to switchers */

class BMD_PUBLIC IBMDSwitcherDiscovery_v9_6_3 : public IUnknown
{
public:
	virtual HRESULT ConnectTo (/* in */ CFStringRef deviceAddress, /* out */ IBMDSwitcher_v9_6_3** switcherDevice, /* out */ BMDSwitcherConnectToFailure* failReason) = 0;
protected:
	virtual ~IBMDSwitcherDiscovery_v9_6_3 () {} // call Release method to drop reference count
};

#endif // defined(__cplusplus)
#endif /* defined(BMD_BMDSWITCHERAPI_V9_6_3_H) */
