/* -LICENSE-START-
 ** Copyright (c) 2014 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#ifndef BMD_BMDSWITCHERAPI_V6_0_H
#define BMD_BMDSWITCHERAPI_V6_0_H

#include "BMDSwitcherAPI.h"

// Interface ID Declarations

BMD_CONST REFIID IID_IBMDSwitcherAudioMixer_v6_0	= /* 58739C15-063E-4FC1-B59B-CC3D9A012D99 */ {0x58,0x73,0x9C,0x15,0x06,0x3E,0x4F,0xC1,0xB5,0x9B,0xCC,0x3D,0x9A,0x01,0x2D,0x99};

#if defined(__cplusplus)

// Forward Declarations

class IBMDSwitcherAudioMixer_v6_0;

/* Interface IBMDSwitcherAudioMixer_v6_0 - Audio Mixer Object */

class IBMDSwitcherAudioMixer_v6_0 : public IUnknown
{
public:
    virtual HRESULT GetProgramOutGain (/* out */ double* gain) = 0;
    virtual HRESULT SetProgramOutGain (/* in */ double gain) = 0;
    virtual HRESULT GetProgramOutBalance (/* out */ double* balance /* [-1.00, 1.00] */) = 0;
    virtual HRESULT SetProgramOutBalance (/* in */ double balance /* [-1.00, 1.00] */) = 0;
    virtual HRESULT SetAllLevelNotificationsEnable (/* in */ bool enable) = 0;
    virtual HRESULT ResetProgramOutLevelNotificationPeaks (void) = 0;
    virtual HRESULT ResetAllLevelNotificationPeaks (void) = 0;
    virtual HRESULT AddCallback (/* in */ IBMDSwitcherAudioMixerCallback* callback) = 0;
    virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherAudioMixerCallback* callback) = 0;
    virtual HRESULT CreateIterator (/* in */ REFIID iid, /* out */ LPVOID* ppv) = 0;
	
protected:
	virtual ~IBMDSwitcherAudioMixer_v6_0 () {} // call Release method to drop reference count
};

#endif      // defined(__cplusplus)
#endif // BMD_BMDSWITCHERAPI_V6_0_H
