/* -LICENSE-START-
 ** Copyright (c) 2024 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#pragma once


#ifndef BMD_CONST
	#if defined(_MSC_VER)
		#define BMD_CONST __declspec(selectany) static const
	#else
		#define BMD_CONST static const
	#endif
#endif

#include "BMDSwitcherAPI.h"

BMD_CONST REFIID IID_IBMDSwitcherMultiView_v9_3_2                 = /* 29D7C6C8-5133-4EBC-9119-5908098BD7B7 */ { 0x29, 0xD7, 0xC6, 0xC8, 0x51, 0x33, 0x4E, 0xBC, 0x91, 0x19, 0x59, 0x08, 0x09, 0x8B, 0xD7, 0xB7 };
BMD_CONST REFIID IID_IBMDSwitcherMultiViewIterator_v9_3_2         = /* F88EDDEF-56C0-4222-A18A-5D11F5400069 */ { 0xF8, 0x8E, 0xDD, 0xEF, 0x56, 0xC0, 0x42, 0x22, 0xA1, 0x8A, 0x5D, 0x11, 0xF5, 0x40, 0x00, 0x69 };
BMD_CONST REFIID IID_IBMDSwitcherRemoteSourceConfiguration_v9_3_2 = /* 4F61EB94-1D24-4344-8EDB-E2946921F5EE */ { 0x4F, 0x61, 0xEB, 0x94, 0x1D, 0x24, 0x43, 0x44, 0x8E, 0xDB, 0xE2, 0x94, 0x69, 0x21, 0xF5, 0xEE };

#if defined(__cplusplus)

// Forward Declarations
class IBMDSwitcherMultiView_v9_3_2;
class IBMDSwitcherMultiViewIterator_v9_3_2;
class IBMDSwitcherRemoteSourceConfiguration_v9_3_2;


/* Interface IBMDSwitcherMultiView_v9_3_2 - MultiView Object */

class BMD_PUBLIC IBMDSwitcherMultiView_v9_3_2 : public IUnknown
{
public:
	virtual HRESULT CanChangeLayout (/* out */ bool* canChangeLayout) = 0;
	virtual HRESULT GetLayout (/* out */ BMDSwitcherMultiViewLayout* layout) = 0;
	virtual HRESULT SetLayout (/* in */ BMDSwitcherMultiViewLayout layout) = 0;
	virtual HRESULT SupportsQuadrantLayout (/* out */ bool* supportsQuadrantLayout) = 0;
	virtual HRESULT GetWindowInput (/* in */ uint32_t window, /* out */ BMDSwitcherInputId* input) = 0;
	virtual HRESULT SetWindowInput (/* in */ uint32_t window, /* in */ BMDSwitcherInputId input) = 0;
	virtual HRESULT GetWindowCount (/* out */ uint32_t* windowCount) = 0;
	virtual HRESULT GetInputAvailabilityMask (/* out */ BMDSwitcherInputAvailability* availabilityMask) = 0;
	virtual HRESULT CanRouteInputs (/* out */ bool* canRoute) = 0;
	virtual HRESULT SupportsVuMeters (/* out */ bool* supportsVuMeters) = 0;
	virtual HRESULT CurrentInputSupportsVuMeter (/* in */ uint32_t window, /* out */ bool* supportsVuMeter) = 0;
	virtual HRESULT GetVuMeterEnabled (/* in */ uint32_t window, /* out */ bool* enabled) = 0;
	virtual HRESULT SetVuMeterEnabled (/* in */ uint32_t window, /* in */ bool enabled) = 0;
	virtual HRESULT CanAdjustVuMeterOpacity (/* out */ bool* canAdjustVuMeterOpacity) = 0;
	virtual HRESULT GetVuMeterOpacity (/* out */ double* opacity) = 0;
	virtual HRESULT SetVuMeterOpacity (/* in */ double opacity) = 0;
	virtual HRESULT CanToggleSafeAreaEnabled (/* out */ bool* canToggleSafeAreaEnabled) = 0;
	virtual HRESULT CurrentInputSupportsSafeArea (/* in */ uint32_t window, /* out */ bool* supportsSafeArea) = 0;
	virtual HRESULT GetSafeAreaEnabled (/* in */ uint32_t window, /* out */ bool* enabled) = 0;
	virtual HRESULT SetSafeAreaEnabled (/* in */ uint32_t window, /* in */ bool enabled) = 0;
	virtual HRESULT GetSupportedSafeAreaTypes (/* out */ uint32_t* supportedSafeAreaTypeFlags) = 0;
	virtual HRESULT GetSafeAreaType (/* in */ uint32_t window, /* out */ BMDSwitcherMultiViewSafeAreaType* type) = 0;
	virtual HRESULT SetSafeAreaType (/* in */ uint32_t window, /* in */ BMDSwitcherMultiViewSafeAreaType type) = 0;
	virtual HRESULT SupportsProgramPreviewSwap (/* out */ bool* supportsProgramPreviewSwap) = 0;
	virtual HRESULT GetProgramPreviewSwapped (/* out */ bool* swapped) = 0;
	virtual HRESULT SetProgramPreviewSwapped (/* in */ bool swapped) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherMultiViewCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherMultiViewCallback* callback) = 0;

protected:
	virtual ~IBMDSwitcherMultiView_v9_3_2 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherMultiViewIterator_v9_3_2 - MultiView Iterator */

class BMD_PUBLIC IBMDSwitcherMultiViewIterator_v9_3_2 : public IUnknown
{
public:
	virtual HRESULT Next (/* out */ IBMDSwitcherMultiView_v9_3_2** multiView) = 0;

protected:
	virtual ~IBMDSwitcherMultiViewIterator_v9_3_2 () {} // call Release method to drop reference count
};

/* Interface IBMDSwitcherRemoteSourceConfiguration_v9_3_2 - Remote Source Configuration Object */

class BMD_PUBLIC IBMDSwitcherRemoteSourceConfiguration_v9_3_2 : public IUnknown
{
public:
	virtual HRESULT AddExternalSource (/* in */ CFStringRef key, /* in */ CFStringRef name, /* in */ bool enabled) = 0;
	virtual HRESULT RemoveExternalSource (/* in */ uint32_t sourceId) = 0;
	virtual HRESULT GetDiscoverable (/* out */ bool* discoverable) = 0;
	virtual HRESULT SetDiscoverable (/* in */ bool discoverable) = 0;
	virtual HRESULT ForceInternetProbe (void) = 0;
	virtual HRESULT GetInternetAddress (/* out */ CFStringRef* internetAddress) = 0;
	virtual HRESULT SetInternetAddress (/* in */ CFStringRef internetAddress) = 0;
	virtual HRESULT GetInternetPort (/* out */ uint16_t* internetPort) = 0;
	virtual HRESULT SetInternetPort (/* in */ uint16_t internetPort) = 0;
	virtual HRESULT GetInternetStatus (/* out */ BMDSwitcherRemoteSourceInternetStatusType* internetStatus) = 0;
	virtual HRESULT GetPortStatus (/* out */ BMDSwitcherRemoteSourcePortStatusType* portStatus) = 0;
	virtual HRESULT CreateIterator (/* in */ REFIID iid, /* out */ LPVOID* ppv) = 0;
	virtual HRESULT AddCallback (/* in */ IBMDSwitcherRemoteSourceConfigurationCallback* callback) = 0;
	virtual HRESULT RemoveCallback (/* in */ IBMDSwitcherRemoteSourceConfigurationCallback* callback) = 0;

protected:
    virtual ~IBMDSwitcherRemoteSourceConfiguration_v9_3_2 () {} // call Release method to drop reference count
};

#endif      // defined(__cplusplus)
